import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA', width: '100%' },
  loadingCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    paddingTop: 60,
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  headerTitle: { fontSize: 24, fontWeight: '800', color: '#fff' },
  headerSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.8)', marginTop: 5 },
  listContent: { padding: 15, paddingTop: 20 },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    // Shadow cho Android & iOS
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  firstPlaceCard: {
    borderWidth: 1.5,
    borderColor: '#FFD700',
    backgroundColor: '#FFFDF0',
  },
  rankBadge: {
    width: 32,
    height: 32,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  rankText: { fontSize: 16, fontWeight: 'bold', color: '#7F8C8D' },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E9ECEF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarInitial: { fontSize: 18, fontWeight: 'bold', color: '#ADB5BD' },
    avatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22, 
    },
  userInfo: { flex: 1 },
  userName: { fontSize: 14, fontWeight: '700', color: '#2D3436' },
  userEmail: { fontSize: 12, color: '#636E72', marginTop: 2 },
  scoreContainer: { alignItems: 'center', minWidth: 60 },
  scoreValue: { fontSize: 20, fontWeight: '800', color: '#FF6347' },
  scoreUnit: { fontSize: 10, color: '#B2BEC3', textTransform: 'uppercase', fontWeight: '600' },

  filterContainer: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  backgroundColor: '#fff',
  marginHorizontal: 15,
  marginTop: -20, // Đẩy lên trên Header một chút
  borderRadius: 12,
  paddingVertical: 10,
  elevation: 4,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
},
filterText: {
  fontSize: 12,
  color: '#7F8C8D',
  fontWeight: '600',
  paddingHorizontal: 15,
  paddingVertical: 5,
},
filterActive: {
  color: '#FF6347',
  borderBottomWidth: 2,
  borderBottomColor: '#FF6347',
},
filterItem: {
  flex: 1,
  alignItems: 'center',
},
activeIndicator: {
  height: 3,
  width: 20,
  backgroundColor: '#FF6347',
  borderRadius: 2,
  marginTop: 4,
},
});